export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const INCREASE_BOOK_IN_CART = "INCREASE_BOOK_IN_CART";
export const DECREASE_BOOK_IN_CART = "DECREASE_BOOK_IN_CART";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
